/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CardCondition = { 'fair' : null } |
  { 'good' : null } |
  { 'mint' : null } |
  { 'poor' : null } |
  { 'near_mint' : null };
export interface CardListing {
  'status' : ListingStatus,
  'title' : string,
  'listingId' : string,
  'createdAt' : Time,
  'description' : string,
  'seller' : Principal,
  'imageUrl' : string,
  'price' : bigint,
  'condition' : CardCondition,
}
export type ListingStatus = { 'active' : null } |
  { 'expired' : null } |
  { 'sold' : null };
export interface OrderRequest {
  'status' : OrderStatus,
  'listingId' : string,
  'createdAt' : Time,
  'orderId' : string,
  'offerPrice' : [] | [bigint],
  'message' : [] | [string],
  'buyer' : Principal,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'rejected' : null } |
  { 'accepted' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createListing' : ActorMethod<
    [string, string, string, bigint, CardCondition, string],
    undefined
  >,
  'createOrderRequest' : ActorMethod<
    [string, string, [] | [bigint], [] | [string]],
    undefined
  >,
  'getActiveListings' : ActorMethod<[], Array<CardListing>>,
  'getBuyerOrderRequests' : ActorMethod<[Principal], Array<OrderRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListingsSortedByCreatedAt' : ActorMethod<[], Array<CardListing>>,
  'getListingsSortedByPrice' : ActorMethod<[], Array<CardListing>>,
  'getOrderRequestsSortedByCreatedAt' : ActorMethod<[], Array<OrderRequest>>,
  'getSellerListings' : ActorMethod<[Principal], Array<CardListing>>,
  'getSellerOrderRequests' : ActorMethod<[Principal], Array<OrderRequest>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markListingSold' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderRequestStatus' : ActorMethod<[string, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];