/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CardCondition = IDL.Variant({
  'fair' : IDL.Null,
  'good' : IDL.Null,
  'mint' : IDL.Null,
  'poor' : IDL.Null,
  'near_mint' : IDL.Null,
});
export const ListingStatus = IDL.Variant({
  'active' : IDL.Null,
  'expired' : IDL.Null,
  'sold' : IDL.Null,
});
export const Time = IDL.Int;
export const CardListing = IDL.Record({
  'status' : ListingStatus,
  'title' : IDL.Text,
  'listingId' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
  'condition' : CardCondition,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'accepted' : IDL.Null,
});
export const OrderRequest = IDL.Record({
  'status' : OrderStatus,
  'listingId' : IDL.Text,
  'createdAt' : Time,
  'orderId' : IDL.Text,
  'offerPrice' : IDL.Opt(IDL.Nat),
  'message' : IDL.Opt(IDL.Text),
  'buyer' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, CardCondition, IDL.Text],
      [],
      [],
    ),
  'createOrderRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'getActiveListings' : IDL.Func([], [IDL.Vec(CardListing)], ['query']),
  'getBuyerOrderRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(OrderRequest)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListingsSortedByCreatedAt' : IDL.Func(
      [],
      [IDL.Vec(CardListing)],
      ['query'],
    ),
  'getListingsSortedByPrice' : IDL.Func([], [IDL.Vec(CardListing)], ['query']),
  'getOrderRequestsSortedByCreatedAt' : IDL.Func(
      [],
      [IDL.Vec(OrderRequest)],
      ['query'],
    ),
  'getSellerListings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(CardListing)],
      ['query'],
    ),
  'getSellerOrderRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(OrderRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markListingSold' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderRequestStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CardCondition = IDL.Variant({
    'fair' : IDL.Null,
    'good' : IDL.Null,
    'mint' : IDL.Null,
    'poor' : IDL.Null,
    'near_mint' : IDL.Null,
  });
  const ListingStatus = IDL.Variant({
    'active' : IDL.Null,
    'expired' : IDL.Null,
    'sold' : IDL.Null,
  });
  const Time = IDL.Int;
  const CardListing = IDL.Record({
    'status' : ListingStatus,
    'title' : IDL.Text,
    'listingId' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
    'condition' : CardCondition,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const OrderRequest = IDL.Record({
    'status' : OrderStatus,
    'listingId' : IDL.Text,
    'createdAt' : Time,
    'orderId' : IDL.Text,
    'offerPrice' : IDL.Opt(IDL.Nat),
    'message' : IDL.Opt(IDL.Text),
    'buyer' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, CardCondition, IDL.Text],
        [],
        [],
      ),
    'createOrderRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'getActiveListings' : IDL.Func([], [IDL.Vec(CardListing)], ['query']),
    'getBuyerOrderRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(OrderRequest)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListingsSortedByCreatedAt' : IDL.Func(
        [],
        [IDL.Vec(CardListing)],
        ['query'],
      ),
    'getListingsSortedByPrice' : IDL.Func(
        [],
        [IDL.Vec(CardListing)],
        ['query'],
      ),
    'getOrderRequestsSortedByCreatedAt' : IDL.Func(
        [],
        [IDL.Vec(OrderRequest)],
        ['query'],
      ),
    'getSellerListings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(CardListing)],
        ['query'],
      ),
    'getSellerOrderRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(OrderRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markListingSold' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderRequestStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };